### ISSUE TITLE
IntentModel extension

### ISSUE THREAD

**Issue by jacekwasilewski** [RankSys/RankSys#13]
Hi @saulvargas,

I am working again on the IntentModel and I would like to change it in a way that it offers not only p(a|u) but as well p(u|a) and p(u). Please take a look at the pull request and let me know if you would be happy with that.
The reason for that is that I would like to explore different definitions of intent models in different contexts and for that I would like to use different probabilities.

Jacek.

**Comment by saulvargas** [comment]
Hi Jacek,
I'll take a look at your suggestions sometime between this evening and tomorrow.
Cheers

**Comment by saulvargas** [comment]
Hi @jacekwasilewski,

It took me a while but finally I have take a look at your proposal. I have some questions/remarks:
- Your model somehow assumes that we know about all the users on the system. While that can be true from a practical point of view (you know everything in your dataset), theoretically I find it hard to justify.
- As a follow up, how does knowing a probability of the user (both total and conditioned to a subtopic) help making some diversification stuff for her?. Maybe I am getting into your ongoing work, but I would like to understand how something like this fits into the idea of an intent model.

Cheers
Saúl

**Comment by jacekwasilewski** [comment]
Hi @saulvargas,

Thanks for your comments.

Probability of user was there for the completeness (I have been doing some probability transformations and it appeared there at some point), however you are right and I aware of that, it does not impact the diversification as it stays the same for a user. I could remove that.

When it comes to your second question - I have broken down the intent model and I have focused on its components and other ways of expressing p(a|u) using these components, still using the feature-based intents. The p(u|a) also might be helpful in the situations where we would like to recommend user to an aspect represented by some items.

Jacek.

**Comment by saulvargas** [comment]
I am fine with your proposal. Please just do the following changes changes:
- Remove the p(u).
- Make the methods in UserIntentModel "public", you made some changes in the code and in your request are "package".
- Change the name of puf to pu_f and pfu to pf_u.

¡Thanks!
Saúl

**Comment by jacekwasilewski** [comment]
I have removed the p(u) and renamed puf and pfu.
As far as I know, there is no need for `public abstract` keywords for methods in interfaces - these are implicitly `public` and the interface is already `public` so those are accessible from any package - https://docs.oracle.com/javase/tutorial/java/IandI/interfaceDef.html. I can add them though.

**Comment by saulvargas** [comment]
Ooops... I forgot it is an interface. Still, please add the "public" keyword for consistency with the rest of the code.

PS I always force myself into adding the appropriate access level modifier even for interfaces so I do not forget to include it in variable and method classes.

**Comment by jacekwasilewski** [comment]
Sure, no problem - done.
