### ISSUE TITLE
How i can create a new instance of SimpleFastUserIndex without the "load"-method?

### ISSUE THREAD

**Issue by timgluz** [RankSys/RankSys#17]
Hi,

i noticed that the constructor in the SimpleFastUserIndex class is protected.
Is there a way i can create a new instance the `SimpleFastUserIndex` without reading file?

I'm building simple Clojure app and i would like to include simple recommender system, but i've no access to underlying disk and all the states are kept in database;

I know that i could write my own Java implementation for UserIndex interface, but i would like to avoid adding more Java into my project.

**Comment by saulvargas** [comment]
Hi Tim,

Normally I try to avoid having mutable objects, therefore this odd restriction. I believe that one possible workaround for this in Java would we something like the following code:

```
Collection<U> users = /// your collection

FastUserIndex<U> userIndex = new SimpleFastUserIndex<>() {
{
    users.forEach(u -> add(u));
}
}
```

I imagine something similar can be done in Clojure?

Otherwise, if could add to the master branch a much simpler "load" method that accepts a collection of users... it is easy but I am not sure I can do that until the weekend (RankSys is nowadays a free-time project).

Cheers
Saúl

**Comment by timgluz** [comment]
Thanks for quick response.

I tried & googled many solutions, i cant create instance of SimpleFastUserIndex, which i could initialize with lambda-fn like your example does. 
I keep getting `CompilerException java.lang.IllegalArgumentException: No matching ctor found for class es.uam.eps.ir.ranksys.fast.index.SimpleFastUserIndex` 

It's fine - i can write my own implementations against UserIndex interface as it's not very big task & Clojure vectors already has similar functionality, i just need to match returning datatypes; 

It'll be perfect to have some kind of static constructor from collection, but it can wait;

**Comment by saulvargas** [comment]
Hi Tim,

I've just added a "better-indexes" branch to the project, which allows the creation of SimpleFast(User|Item|Feature)Index objects with Stream of objects.

I'll probaby merge with the master branch whenever I find some time to add some unit test for these new changes. You can use meanwhile this temporary branch by setting the version of the project to "better-indexes-SNAPSHOT".

Cheers
Saúl

**Comment by timgluz** [comment]
Thanks, 

i will try out tonight .

**Comment by saulvargas** [comment]
The "better-indexes" branch has been merged with the master branch.
