### ISSUE TITLE
Normalisation in LambdaReranker

### ISSUE THREAD

**Issue by jacekwasilewski** [RankSys/RankSys#24]
Hi @saulvargas,

I wanted to ask you if there is any particular reason why the normalisation for relevance and novelty is done every time an item is selected by the re-ranker, not once for all entries? As far as I am concerned, single normalisation should be enough.

I need to check the actual values that the re-ranker would output and the current normalisation changes slightly the formulation I think.

Thanks,
Jacek.

**Comment by jacekwasilewski** [comment]
Ok, I see the reason why we cannot (I think) normalise the scores just once (or calculate the Stats once).
But if the Stats are gathered before every single selection, does not it mean that the re-ranking objective:
(1 - lambda) \* relevance + lambda \* novelty
is changed and that the proportion between relevance and novelty is not exactly lambda any more?

**Comment by saulvargas** [comment]
Hi @jacekwasilewski,

LambdaReranker is a greedy algorithm, that means that, after each iteration, at least one of the scoring functions changes completely as it has to take into account the newly added item. Also, the pool of items to select from decreases and defines, somehow, two new distributions with different norms and variances. These two facts arguably justify the need for new normalisation parameters.

In practice, we chose to do things this way after testing lots of different choices for normalisation. This choice for normalisation achieves a smooth transition when moving the lambda parameter from 0.0 to 1.0 while it does not add a high cost in terms of computations.

Regarding alternative/better ways of combining relevance and novelty scores, I believe that Ozdemiray and Altingovde addressed this issue (ini the context of IR diversificatoin) in their 2015 JASIS paper: http://onlinelibrary.wiley.com/doi/10.1002/asi.23259/abstract;jsessionid=F8498BC8EF3D2892490D46404489BC0C.f03t04

Saúl

**Comment by jacekwasilewski** [comment]
Thanks Saul, that's really helpful!
