### ISSUE TITLE
Needs help with Novelty & Diversity Metrics

### ISSUE THREAD

**Issue by vinceRicchiuti** [RankSys/RankSys#27]
Hi All, 
i know that this is my issue but i'm using this tool for my thesys project and i have to evaluate the novelty and diversity of the recommendations of my RecSys. Since i use the example find here, i notice that changing the file of recommendations, values of metrics are NaN or remain the same. I need to evaluate for closing my degree work. Can anyone help my doind this? Thanks in advance

**Comment by saulvargas** [comment]
Hi @vinceRicchiuti 

Thanks for you interest in RankSys. Please provide me with some more details about what you are trying to do, including:
- Version of RankSys that you are using.
- Commands that you are running.
- Files that you are using as input (or a representative fraction from it).
- The output that you get.

Cheers
Saúl

**Comment by vinceRicchiuti** [comment]
Can i write to your email that i found in your account details?
Vincenzo

**Comment by saulvargas** [comment]
Sure. Would it be OK if I publish afterwards the main findings of this issue provided that I find them useful for the rest of the users of RankSys?

**Comment by vinceRicchiuti** [comment]
Sure! It's only for not writing unuseful things before understanding what i am doing wrong.

**Comment by saulvargas** [comment]
Solved offline.
Issues #28 #29 #30 created as consequence.
