### ISSUE TITLE
Aspect models - proposal

### ISSUE THREAD

**Issue by jacekwasilewski** [RankSys/RankSys#31]
Hi @saulvargas,

I would like to propose a change in the IntentModel and the xQuAD/RxQuAD - I will send the code later, after polishing it a bit.

First, after working more with the intent-aware framework, the change from #13 does not make sense, I mean, having the method for p(u | f) - not a part of the aspect model.

The aspect model (e.g. in Hofmann, Puzicha, & Jordan, 1999) is defined as the p(a | u) and the p(i | a) (or p(i | a, u) or p(rel | i, a, u)). Right now, the IntentModel handles p(a | u), and p(i | a, u) and p(rel | i, a, u) are implemented in the xQuAD and RxQuAD. I would like to take out the pif() methods out and put them in separate classes. Then the xQuAD would become only a way to combine scores with the IA-Select to create rankings, and we could easily use different models for p(a | u) and p(i | a, u).
I am not sure about the naming, but IntentModel could become the UserAspectModel and the p(i | a, u) could be names as ItemAspectModel.

Let me know what you think about the above.

Thanks,
Jacek.

**Comment by jacekwasilewski** [comment]
Hi @saulvargas,

I have pushed the first version of the code, how it could look like. It is not ideal, there is one thing that I do not like about it but I am not sure how else that could be solved - maybe you will have an idea.

So, what I did:
- I removed p(u | a) from the intent model
- I created an aspect model class that uses already existing intent model classes - user aspect model kind of decorates user intent model; it offers exactly what the user intent model offers plus the p(i | a)
- I moved the definitions for p(i | a) from xQuAD and RxQuAD and placed them in ScoresAspectModel and ScoresRelevanceAspectModel respectively; I named them "Scores" as they take recommendation scores to calculate the probabilities
- as the xQuAD and RxQuAD do not need pif() methods any more, the only difference in their implementation is the redundancy tolerance parameter, so I created AlphaXQuAD and XQuAD becomes a simple wrapper

I checked and previous and proposed implementation return the same results.

Time-wise, for ML-1M the proposed implementation is approximately 2s slower (21s compared to 19s in my experiments) for one re-ranking of UB recommendations - default settings for UB and xQuAD.
I expect that the reason for that is in the way how I am handling scores - first that I read them again, second that I store them for random access and that I randomly access them.

Other option could be to have an interaction between UserAlphaXQuAD and UserAspectModel but I could come up with something simple that would not constrain the UserAspectModel by assuming that we always have access to scores. Other idea I had to have a builder or a factory but that might be an over-engineering. Maybe you have a better idea how to handle scores?

Jacek.

**Comment by saulvargas** [comment]
Hi @jacekwasilewski 

Thanks for the PR. It is definitely a problem that the scores need to be pre-computed before applying the diversification step. First, it prevents the xQuAD from being applied in an online manner. Second, you need a lot of memory (specially for datasets where you have 100Ks users) to store them. Third, that is not the intended use of the PrefereceData structure.

I am delighted with generalising/extending/improving the code in xQuAD and RxQuAD, but not at the cost of breaking its versatility.

Thanks again!
Saúl

**Comment by jacekwasilewski** [comment]
Hi @saulvargas,

I changed the PR that these three issues are solved. So the whole change would be about moving the pi_f methods out to form an aspect model. There is a `initializeWithItems` method to pass items to the aspect model. I though it is not elegant as you need to know to call it but on other hand there is only one aspect-based re-ranker right now and probably there will not be many, so it should not be a huge problem.

Why do I need that change? I have been working on different aspect models and would like to add them to the project. But that assumes the pi_f method is not a part of the xQuAD classes.

Time-wise and memory-wise, the current PR version should perform as well as the original code. Quick experiments confirm that.

Let me know what you think.

Thanks,
Jacek.

**Comment by saulvargas** [comment]
Hi @jacekwasilewski 

It definitely took me too much time to get back to you, I'm really sorry!!!

I am mostly OK with your proposed changes, see if the following commit on top of your PR makes sense: https://github.com/RankSys/RankSys/commit/b3219776b14dc0834a73ef5e6f4ab63e307ea31f

**Comment by jacekwasilewski** [comment]
Hi @saulvargas 

No worries!
I am fine with the changes.

Jacek.
