### ISSUE TITLE
Documenting aspect models

### ISSUE THREAD

**Issue by saulvargas** [RankSys/RankSys#33]
Hi @jacekwasilewski 

I am updating the wiki for the version 0.4.3 of RankSys which features, among other things, your proposed Aspect Model. Would you mind taking a look at the documentation in the wiki (https://github.com/RankSys/RankSys/wiki/Novelty-and-Diversity#intent-aware-diversity) to see if you could update it to summarise briefly (one or two sentences would suffice) what are the aspect models about?

Thanks

**Comment by jacekwasilewski** [comment]
Hi @saulvargas 

Sure, consider it done.

**Comment by jacekwasilewski** [comment]
Hi @saulvargas 

Took me a while but I changed the documentation for Intent-Aware Diversification to reflect the code. Take a look and let me know if it is fine.

**Comment by saulvargas** [comment]
It looks great! Thanks!
