### ISSUE TITLE
Examples for PM and Binomial Diversification Frameworks

### ISSUE THREAD

**Issue by jacekwasilewski** [RankSys/RankSys#36]
Hi @saulvargas 

I was wondering if you could add examples of use of the PM and Binomial Diversification, that would match your results from the paper or the thesis - I was trying to reproduce some of your experiments on the ML1m dataset but I was getting really strange results, not even close to what you obtained in your paper or the thesis.
What should go as the `PreferenceData<U, I> recommenderData` to the BinomialModel? Documentation suggests preferences (so train data) but variable name sounds like recommendations?

Jacek.

**Comment by saulvargas** [comment]
Hi @jacekwasilewski 

Let me revisit some time this weekend the binomial diversification stuff in RankSys. I will try to reproduce part of the results by myself and provide you with the configuration that is required.

That "recommenderData" means training preferences. In very early versions of RankSys, the PreferenceData interface was called RecommenderData, hence the (now inappropriate) name.

Regards
Saúl

**Comment by saulvargas** [comment]
Hi again,

So I was able to reproduce a couple of rows of table 6.9 in my thesis. This is how they look like:

|  | Cov | Red | Div |
| --: | --: | --: | --: |
| Pop | 0.8429 | 0.2327 | 0.1986 |
| iMF | 0.7869 | 0.3584 | 0.2882 |
| UB | 0.8195 | 0.3292 | 0.2765 |
| IB | 0.7971 | 0.3180 | 0.2580 |

As you can see, little difference wrt what you can see in the chapter.

The code I used can be found here: https://gist.github.com/saulvargas/f8f7a2335a9d9f49bc1540249c453b18

I might suspect that your problem might be related to not using the full dataset to compute the binomial model?

Regards
Saúl

**Comment by jacekwasilewski** [comment]
Hi @saulvargas 

Thanks a lot! Hmm, code looks similar to what I have.. need to check everything once more. Actually I was more interested in the re-ranker but if my BinomialModel is correct then it should work as expected.

One more question - when you were implementing the proportionality re-ranker, which uses the BinomialModel, did you get results somewhere close to what they reported in their paper? I know they evaluate it on the IR datasets but maybe you had a chance to check that.

What I am seeing right now is that if I re-rank e.g. UB on ML1M, for lambda from 0.0 to 1.0 with step of 0.1, I get the lowest precision for lambda=0.0 - 0.14, then it is growing up to 0.19 for lambda=1.0. I saw in their paper that it is not a linear combination of score but I am kind of confused and I was wondering if that is what I was supposed to get.

Thanks,
Jacek.

**Comment by saulvargas** [comment]
Hi Jacek,

No, I did not check the PM implementation on search tasks.

As you see, the PM in recommendation datasets seems to be working the best when PM. I do not remember the exact reason, but I do remember I run all the experiments in the RecSys paper and my thesis using lambda = 1.0 there.

I am going to try to reproduce some of the results of the BinomialDiversity re-ranker in the ML1M data. I will let you know.

**Comment by saulvargas** [comment]
So these are the results:

(lambda=1.0, alpha = 0.5, metric cutoff = 20)
imf	prec	0.23214640609473117
imf	binom-red	0.35838774700812975
imf	binom-div	0.2881664905629823
imf	binom-cov	0.7868894280720375
hkv+div	prec	0.1182842000662467
hkv+div	binom-red	0.7807679244862935
hkv+div	binom-div	0.7648955379393582
hkv+div	binom-cov	0.9788536191600012

As you can see, I can reproduce the precision and BinomCov values of the re-ranker, although the other two metrics (BinomRed and BinomDiv) differ significantly. I am unsure whether I made any change/fix to the code that altered the results, but I would expect these changes do not alter too much the "big picture" of the results.

This is the code: https://gist.github.com/saulvargas/d02078d1ae4cf827d1bdcd31ec0333ed

**Comment by jacekwasilewski** [comment]
Hi @saulvargas,

Thanks a lot, that is really useful! I put that problem aside for a while but when I get back to it, I will compare if what I get is close to what you have - it should be.

Thanks again!
Jacek.
