### ISSUE TITLE
Document CPLSA in Wiki

### ISSUE THREAD

**Issue by saulvargas** [RankSys/RankSys#40]
Hi @jacekwasilewski 

I am updating some bits of the wiki. Whenever you have some time (no hurries at all!!!), could you please add a short explanation of your CPLSA code? You may create a separate page or add it to here https://github.com/RankSys/RankSys/wiki/Novelty-and-Diversity (whatever you find more convenient).

Thanks!

**Comment by jacekwasilewski** [comment]
Hi @saulvargas 
I thought I commented on that - of course, I will add a short explanation. That should happen soon...ish ;)

Jacek.

**Comment by jacekwasilewski** [comment]
Hi @saulvargas 

I rewrote the Intent-aware section a bit, check if it is fine or if I should add something more.

Jacek.

**Comment by saulvargas** [comment]
Thanks @jacekwasilewski 

Yes, I just needed a specific mention to your cpLSA code.
