### ISSUE TITLE
java 8 compatibility issue

### ISSUE THREAD

**Issue by 8-chems** [RankSys/RankSys#45]
hey vargas,
I finally installed maven and tried a compilation, i am on debian, tried both open pre-installed jdk and java 8 (1.8.0_102 and 1.8.0_131), in both i am facing an issue with ranksys-fast and ranksys-format with maven 3.5.0

![aaaa](https://user-images.githubusercontent.com/10013032/28444010-d9f9e746-6db1-11e7-8818-15c22c2e972c.png)

**Comment by saulvargas** [comment]
Hi,

Sorry for the delay, an issue with my mail filters made me lose Github notifications.

Please let me know what version of RankSys are you trying to use exactly, and what do you get when you run from the command line:
``mvn clean package``

Alternatively, you already have in maven central a compiled version of RankSys in its stable version.

**Comment by 8-chems** [comment]
hey, I have downloaded the whole project from github, so it should be the last version, how could I used the pre compiled version from maven ? thanks a lot for your answer

**Comment by 8-chems** [comment]
I did get jar files from maven, thank you very much vargas : )
