### ISSUE TITLE
could you please share some data samples ?

### ISSUE THREAD

**Issue by 8-chems** [RankSys/RankSys#46]
hey m trying to run some examples, could you share some data samples  related to:

        String trainDataPath = args[0];
        String testDataPath = args[1];
        String featurePath = args[2];
        String recIn = args[3];

**Comment by 8-chems** [comment]
I have found in another issue that train and test data are in the same format as in movielens data files, so how about features and userpath/itempath ?
        String userPath = args[0];  
        String itemPath = args[1];
        String featurePath = args[2];
        String trainDataPath = args[3];
        String testDataPath = args[4];
        String featureDataPath = args[5];

**Comment by jacekwasilewski** [comment]
Hi @ChemsEddineBerbegue,

Sorry, I missed this thread. Not sure if you still need help. Anyway.
Probably raw MovieLens dataset will not work, you have to transform it a bit to run the examples.
`trainDataPath` and `testDataPath` refer to two spilts of the interactions dataset, 3-4 columns (user, item, rating, timestamp), tab-separated.
`featureDataPath` (in the first question `featurePath`) refers to a file with item-features pairs; again tab-separated, first column is item, second could be e.g. a string (like genre Drama).
`recIn` refers to a file with generated recommendations, e.g. produced by the RankSys framework.
`userPath`, `itemPath` and `featurePath` (from the second question) are files that each contains one column with, respectively, all users, items and features.
If we consider the MovieLens 1M dataset, you would have to change the field separator in the files to get `trainDataPath` and `testDataPath` (from `::` to `\t`). There is a file (`movies.dat` I believe) from which you can get item-feature pairs for `featureDataPath`. `userPath` file would contain a list of all ~6k users, `itemPath` a list of all ~4k movies and `featurePath` (from the second question) a list of 18-19 genres that they use.

Hope this helps.
Jacek

**Comment by 8-chems** [comment]
Thank you, that worked for me
