### ISSUE TITLE
Threshold

### ISSUE THREAD

**Issue by sumitsidana** [RankSys/RankSys#47]
Hi, @jacekwasilewski, @saulvargas 

I needed a little help of yours in tuning a parameter for a problem which I am trying to solve.

In Class, es.uam.eps.ir.ranksys.examples.MetricExample, there is a parameter `threshold` as args[4]. Is that to be tuned or taken `0.5` or some other value for all the BinaryRelevanceModels?

Thanks
Sumit

**Comment by jacekwasilewski** [comment]
Hi @sumitsidana,
I would say it is up to you to decide what rating you treat as a relevant/positive feedback. If e.g. you have ratings on a scale of 1-5, then you could use a threshold of e.g. 4, so 4s and 5s are considered as positive feedback.

**Comment by sumitsidana** [comment]
Hi @jacekwasilewski 

Thank you very much. It makes a lot clearer after your post.
