### ISSUE TITLE
Could you please help me with some info about data example?

### ISSUE THREAD

**Issue by thacianacerqueira** [RankSys/RankSys#51]
Hello,

I'm trying to run some examples. Could you please help me with some info about it:

1 – In issues #46, you said that “ trainDataPath and testDataPath refer to two spilts of the interactions dataset, 3-4 columns (user, item, rating, timestamp), tab-separated”. 

The rating value could be from 0 to hundreds? 
The information in  trainDataPath and testDataPath could be different from rating and timestamp? 

2 – Still in issues #46, you said that “ featureDataPath refers to a file with item-features pairs”. It would be possible to have more than a feature for the same item, e.g. genre, director’s name and others?

3 – Which class defines featureDataPath = args[5]? Because I did not find the parameter neither in  RecommenderExample or MetricExample. I found just featurePath = args[2] in MetricExample.

4 - In RecommenderExample, there is a parameter called “q” used in  user-based and item-based nearest neighbors. What does it (q) means? It represents overllaping?

Thanks in advance.

**Comment by saulvargas** [comment]
Hi,

1) Ratings in SimpleFastPreferenceData (the PreferenceData instance used in the examples) can contain any double value. In the default implementation, the third field can be any numerical value, and the fourth field (typically timestamp) is actually ignored in most subclasses of PreferenceData.

2) Yes, you can have more than one genre per item, or different types of attributes mixed. However, most algorithms using FeatureData assume that the features belong to the same category (e.g. genres only).

3) You need a FeatureData object when you want to use some of the diversity-aware metrics and rerankers of RankSys. You can find the documentation about this in the wiki and javadocs.

4) q is the paremeter defined in section 3.3 in [this paper](https://dl.acm.org/citation.cfm?id=2507189&dl=ACM&coll=DL), you can just leave it at q=1 (standard kNN) or try with higher value which may lead to higher accuracy

Hope this helps, let us know if you have further questions.

**Comment by thacianacerqueira** [comment]
Thank you, that worked for me.
